### ISSUE TITLE
Time rescaling needed for Dirac coalescent

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#186] opened 2017-04-12 20:17 UTC
We need to rescale the time in the Dirac coalescent into generations. Currently we're scaling by 4Ne, which is wrong.

Similarly, our input recombination rate is in units of generations, but is not being rescaled into the appropriate time units for the Dirac coalescent.

**Comment by eldonb** [comment] 2017-04-13 07:13
we rescale by N^2 (N squared); then we have the mixture process of  multiple mergers  +  the kingman part.   However, recombination is scaled in units of N; this follows from  the generation of 1  recombinant offspring at most each generation.  

bjarki

**Comment by jeromekelleher** [comment] 2020-01-19 19:55
See the code [here](https://github.com/tskit-dev/msprime/blob/master/lib/msprime.c#L5453).

At moment we're scaling by N in one direction and N^2 in the other, which can't be right...

**Comment by JereKoskela** [comment] 2020-02-25 14:40
> we rescale by N^2 (N squared); then we have the mixture process of multiple mergers + the kingman part. However, recombination is scaled in units of N; this follows from the generation of 1 recombinant offspring at most each generation.

Are you sure that rescaling by N^2 is right @eldonb? Granted, the pre-limiting Moran model scales to the ARG when time is scaled in units of N^2 steps. But I thought the usual convention for "a generation" in a Moran model was N steps, so that everyone gets replaced once on average. Overall, that would leave a scaling factor proportional to N for both time and recombination rates when converting coalescent time to generations.

**Comment by eldonb** [comment] 2020-02-26 15:46
N^2 is the correct scaling of the time in a Moran-type model -  it  clearly follows from the scaling of c_N, the probability of  two individuals (gene  copies) sampled at the same time having the same parent; however,  we need to scale  recombination by N, this follows from the arrangement of having recombination occurring in conjunction with a "small" reproduction event, when  only one offspring is produced, an event which happens with probability 1 - \epsilon_N, and  \epsilon_N \to 0 as N \to \infty.   So the "effective size" Ne  is of order N^2.  The timescaling is discussed in the Genetics ARG-paper with Birkner and Blath; I will dig this out and write it up in the section part

**Comment by JereKoskela** [comment] 2020-02-26 16:01
I completely agree, and if we were converting between coalescent time and discrete Moran time steps, then everything would be crystal clear. But that's not the conversion we are making - we are converting between coalescent time and something we call "generations".

For the Wright-Fisher and Schweinsberg models it makes sense to define "1 = generation = 1 discrete time step", but I'm not sure whether that definition is the best or most natural for a Moran model. And if we choose to define generations differently, e.g. "1 generation = N time steps", then that needs to be reflected in the scaling.

**Comment by eldonb** [comment] 2020-02-26 17:01
this is the same as the way I think about converting back and forth with the time in these models, that is:
one coalescent time unit corresponds to  1/c_N "generations" (discrete time steps), and 
one generation corresponds to  c_N  coalescent time units - 
so if   1/c_N corresponds to  N^2 generations (discrete time steps)  for the Moran model then so be it.  I would be consistent in the  way we convert time, even if it means  converting  to N^2 generations; then I think we would be consistent in what we call "generation".

**Comment by jeromekelleher** [comment] 2020-03-24 09:36
#898 added some unit tests to ensure that the model time changes are inverses. There's a test that was commented out that should be enabled when we fix the dirac scalings.

(Also, amazed that there's been > 700 issues and PRs on msprime since this was opened... we really should ship this code!)

**Comment by jeromekelleher** [comment] 2020-03-24 14:21
cc @TPPSellinger

**Comment by TPPSellinger** [comment] 2020-03-24 15:02
Hi all, I have a quick question. Assume we have a constant  population size and  a mutation rate equal to the recombination rate. If we chose to the coalescent rate to be scaled in N². We would need to scale recombination rate by N, right? Would the following "simple" tests be sufficient to assure the dirac coalescent simulator to be correct :  
-Check SFS is correct (assume independent loci, so no recombination) in order to check coalescent rate (and mutation process)  is correct 
- Because mutation rate is equal to recombination rate, for every mutation we should, in expectation, have a recombination. So the expected number of segregating sites (theta) should be equal to the number of different genealogies. (Has it already been tested?)

This way we know that everything has correctly been scaled and the simulator works, no ?

**Comment by JereKoskela** [comment] 2020-03-24 15:19
Checking the SFS is certainly one of the better ways to ensure that the merger rates are correct, and I like your argument for why it is also evidence of a correct recombination rate @TPPSellinger. I'd say that is a good plan.

**Comment by TPPSellinger** [comment] 2020-03-24 15:38
Okay then here is what I will  (try) to do :
-make sure change in rates/generations are inverse function.
-make sure SFS is correct  (the test is already implemented in verification.py, right ? ).
-I will add a quick check in verification.py to make sure that segregating sites and number of genealogies have same expected value. 

Does this Sounds good ? 

With a bit luck everything is done by the end of the week.

**Comment by JereKoskela** [comment] 2020-03-24 15:43
Yes, that sounds fine at least to me. I hadn't noticed the expected SFS code in verification.py - that looks very helpful.

**Comment by TPPSellinger** [comment] 2020-03-24 15:52
There are two functions in verification.py:  
    verifier.add_xi_dirac_expected_sfs()
    verifier.add_xi_beta_expected_sfs()
I don't really know what they do. I assume they check the expected SFS against the simulated one. 
And I also assume they worked. I never asked myself if they are actually correct or if the results were good...

**Comment by jeromekelleher** [comment] 2020-03-24 16:27
@shajoezhu added these SFS checks to verification.py; I think they are based on analytical results for special cases.

**Comment by jeromekelleher** [comment] 2020-04-21 13:45
I think this can be closed now @JereKoskela ?

**Comment by JereKoskela** [comment] 2020-04-21 13:46
> I think this can be closed now @JereKoskela ?

Yes, I think this is done, as are the two issues on statistical tests for Dirac and Beta coalescents.

**Comment by JereKoskela** [comment] 2020-04-21 13:49
Closed in [#953](https://github.com/tskit-dev/msprime/pull/953)

**Closed by JereKoskela** 2020-04-21 13:49 UTC
