### ISSUE TITLE
Duplicate markers?

### ISSUE THREAD

**Issue by biona001** [tskit-dev/msprime#842] opened 2019-12-05 21:56 UTC
Hello,

I have a script that simulates haplotypes using `msprime` and outputs a VCF file. 

```
import msprime, sys

# parameters
sample_size = int(sys.argv[1])
effective_population_size = int(sys.argv[2])
sequence_length = int(sys.argv[3])
recombination_rate=float(sys.argv[4])
mutation_rate=float(sys.argv[5])
seed = int(sys.argv[6])

# run the simulation
tree_sequence = msprime.simulate(sample_size=sample_size, Ne=effective_population_size, length=sequence_length, recombination_rate=recombination_rate, mutation_rate=mutation_rate, random_seed=seed)

# print results
with sys.stdout as vcffile:
        tree_sequence.write_vcf(vcffile, 2) # 2 is for diploid
```

Calling the following script in terminal via 
```
python3 msprime_script.py 4000 10000 5000000 2e-8 2e-8 2019 > simulation.vcf
```
shows that marker `101742` is repeated at least twice. Is this intended behavior or did I do something wrong? Is there a way to avoid outputting duplicate markers? In addition, is there a way to output the REF/ALT alleles as letters (A, T, C, G) instead of 0 and 1? Softwares I'm using (e.g. Beagle 5) requires letters as inputs.

**Comment by jeromekelleher** [comment] 2019-12-06 09:45
The duplication here is due to the fact that msprime simulates "infinite sites" mutations with floating point positions (which are guaranteed to be unique), but VCF requires site positions to be integers. The [write_vcf](https://tskit.readthedocs.io/en/latest/python-api.html#tskit.TreeSequence.write_vcf) method by default rounds positions to the nearest integer. If you wish to avoid duplicates, you can use ``position_transform="legacy"``, but this has it's own quirks. Please see the documentation for ``position_transform`` for details.

If you wish to output nucleotides, you can do something like
```python
ts = msprime.simulate(sample_size=sample_size, Ne=effective_population_size, length=sequence_length, recombination_rate=recombination_rate, random_seed=seed)
model = msprime.InifinteSites(msprime.NUCLEOTIDES)
ts = msprime.mutate(ts, mutation_rate=mutation_rate, model=model)
```
See the documentation for [mutate](https://msprime.readthedocs.io/en/stable/api.html#simulating-mutations) for details.

I'm going to close this issue, as the above is expected behaviour.

**Closed by jeromekelleher** 2019-12-06 09:45 UTC
