### ISSUE TITLE
Sampling only historical lineages produces forest

### ISSUE THREAD

**Issue by terhorst** [tskit-dev/msprime#1477] opened 2021-02-12 13:48 UTC
```
>>> msp.simulate(samples=[msp.Sample(0, 0.), msp.Sample(0, 1.)]).first().as_dict_of_dicts() # expected
{2: {0: {'branch_length': 1.167618823851077},
  1: {'branch_length': 0.16761882385107696}},
 0: {},
 1: {}}
>>> msp.simulate(samples=[msp.Sample(0, 0.0001), msp.Sample(0, 1.)]).first().as_dict_of_dicts() # unexpected!
{0: {}, 1: {}}

**Comment by terhorst** [comment] 2021-02-12 13:48
This is on msprime 0.7.4.

**Comment by petrelharp** [comment] 2021-02-12 14:13
Thanks for the report! I think this is a duplicate of #983, and so has been dealt with. Re-open if not?

**Closed by petrelharp** 2021-02-12 14:13 UTC
