### ISSUE TITLE
deprecation warnings don't use the DeprecationWarning category

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#1207] opened 2020-09-24 17:08 UTC
Deprecation warnings from, e.g. the DeprecationFacade and recombination map's num_loci, use `warnings.warn`, but don't set `category=DeprecationWarning`. This is a fairly easy change, but maybe there's a reason they don't use this warning category? An argument in favour of using the category is for easy filtering in downstream applications (it's nice to see these as an application developer, but less nice if users start seeing them when they upgrade a dependency).

**Comment by petrelharp** [comment] 2020-09-24 17:14
I ended up using FutureWarning instead of DeprecationWarning in pyslim because the latter didn't actually appear. This is by design: they differ in [intended audience](https://docs.python.org/3/library/warnings.html); if you want a warning that makes users change their scripts, you want FutureWarning, I believe. DeprecationWarning and FutureDeprecationWarning are both ignored by default.
![Screenshot from 2020-09-24 10-12-33](https://user-images.githubusercontent.com/1046249/94177578-9d688b80-fe4e-11ea-8d82-a0f6518d4099.png)

**Comment by jeromekelleher** [comment] 2020-09-25 07:40
#1194 is related.

**Comment by jeromekelleher** [comment] 2021-03-17 19:30
Closed in #1536

**Closed by jeromekelleher** 2021-03-17 19:30 UTC
