### ISSUE TITLE
Better error message needed for missing populations

### ISSUE THREAD

**Issue by eaton-lab** [tskit-dev/msprime#858] opened 2020-01-17 20:41 UTC
I'm having trouble implementing a model with multiple populations (includes `MassMigration`) while also using ancient samples (includes `samples=[...]`). I am able to implement either one individually but not the two features together:

```python
import msprime as ms

# two population model, one tip at 0 the other at 500, and population divergence at 5000. 
sim = ms.simulate(
    num_replicates=1,
    samples=[
        ms.Sample(population=0, time=0),
        ms.Sample(population=1, time=500),
    ],
    demographic_events=[
        ms.PopulationParametersChange(
            time=500, initial_size=1000, population=1),
        ms.PopulationParametersChange(
            time=0, initial_size=1000, population=0),
        ms.MassMigration(
            time=5000, source=0, dest=1),
        ms.PopulationParametersChange(
            time=5000, initial_size=1000, population=0)
    ],
)

# test it
for i in next(sim).trees():
    print(i)
``` 

This raises the following error:
```python
---------------------------------------------------------------------------
InputError                                Traceback (most recent call last)
<ipython-input-121-1d37f047a9b0> in <module>
     18 
     19 # test it
---> 20 for i in next(sim).trees():
     21     print(i)

~/miniconda3/envs/py36/lib/python3.6/site-packages/msprime/simulations.py in _replicate_generator(sim, mutation_generator, num_replicates, provenance_dict, max_time)
    116     while j < num_replicates:
    117         j += 1
--> 118         sim.run(max_time)
    119         tree_sequence = sim.get_tree_sequence(mutation_generator, provenance_record)
    120         yield tree_sequence

~/miniconda3/envs/py36/lib/python3.6/site-packages/msprime/simulations.py in run(self, max_time)
    663         if self.random_generator is None:
    664             raise ValueError("A random generator instance must be set")
--> 665         self.ll_sim = self.create_ll_instance()
    666         for event in self.model_change_events:
    667             self.ll_sim.run(event.time)

~/miniconda3/envs/py36/lib/python3.6/site-packages/msprime/simulations.py in create_ll_instance(self)
    654             segment_block_size=self.segment_block_size,
    655             avl_node_block_size=self.avl_node_block_size,
--> 656             node_mapping_block_size=self.node_mapping_block_size)
    657         return ll_sim
    658 

InputError: Population ID out of bounds.
```

Any help or advice is appreciated, thanks!

**Comment by petrelharp** [comment] 2020-01-18 06:59
Hello! That's a confusing one. The problem is that there's only one population by default, so when it comes to a reference to population 1, it throws an error. To have more than one population, you need to pass in the `population_configurations = ` argument, like so (simplified somewhat):
```
sim = ms.simulate(
    samples=[
        ms.Sample(population=0, time=0),
        ms.Sample(population=1, time=500),
    ],
    population_configurations = [
        ms.PopulationConfiguration(),
        ms.PopulationConfiguration()
    ],
    demographic_events=[
        ms.MassMigration(
            time=5000, source=1, dest=0)
    ],
)

print(sim.num_trees)
```

Hope that helps! Please close this issue if it sorts out your problem.

**Comment by molpopgen** [comment] 2020-01-18 19:38
Does the demography debugger catch this?

**Comment by molpopgen** [comment] 2020-01-18 21:32
> Does the demography debugger catch this?

Yes, it throws an error on the `demographic_events` with the ID out of bounds

**Comment by jeromekelleher** [comment] 2020-01-19 20:58
It's not the most helpful error message though: perhaps we should change it?

**Comment by molpopgen** [comment] 2020-01-19 21:02
Yeah, one thing I noticed is that "samples" stuff can't get passed to the debugger.  It'd be cool to have it say "trying to sample from a deme that doesn't exist" or something like that.

**Comment by molpopgen** [comment] 2020-01-19 21:02
Yeah, one thing I noticed is that "samples" stuff can't get passed to the debugger.  It'd be cool to have it say "trying to sample from a deme that doesn't exist" or something like that.

**Comment by jeromekelleher** [comment] 2020-01-20 09:46
OK, I've renamed the issue and pushed it into the next milestone.

**Comment by petrelharp** [comment] 2020-01-20 20:08
It's saying the right thing; but it could say *where* the bad pop ID was referenced.

**Comment by eaton-lab** [comment] 2020-01-20 21:35
Thank you for the quick response. This seems to solve our problem in a simple way.

I will leave it open for you to decide about the error messages issue.

**Closed** 2020-03-24 19:58 UTC
